In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from sklearn.preprocessing import StandardScaler
pd.set_option('max_rows', 200)
pd.set_option('max_columns', 200)
sns.set_style('ticks')

In [11]:
ride = pd.read_csv("data/ride_count.csv")
weather = pd.read_csv("data/weather.csv")

In [12]:
weather['DATE'] = pd.to_datetime(weather['DATE'])

In [13]:
march_weather = weather.loc[weather['DATE'].dt.month == 3]
jul_weather = weather.loc[weather['DATE'].dt.month == 7]
oct_weather = weather.loc[weather['DATE'].dt.month == 10]
dec_weather = weather.loc[weather['DATE'].dt.month == 12]

In [20]:
march_weather

         DATE  TMIN  TAVG  TMAX  SNOW  PRCP  SNWD   AWND
59 2017-03-01    48    51    61   0.0  0.01   0.0  11.63
60 2017-03-02    37    52    62   0.0  0.00   0.0  25.50
61 2017-03-03    25    37    42   0.0  0.00   0.0  18.34
62 2017-03-04    18    27    34   0.0  0.00   0.0  20.80
63 2017-03-05    16    24    38   0.0  0.00   0.0  13.65
64 2017-03-06    22    32    42   0.0  0.00   0.0   8.05
65 2017-03-07    42    44    50   0.0  0.11   0.0  10.51
66 2017-03-08    46    52    61   0.0  0.05   0.0  16.55
67 2017-03-09    46    55    64   0.0  0.00   0.0  19.46
68 2017-03-10    24    42    49   2.4  0.26   0.0  17.45
69 2017-03-11    18    25    29   0.0  0.00   2.0  18.57
70 2017-03-12    20    25    32   0.0  0.00   1.2  18.34
71 2017-03-13    20    26    34   0.0  0.00   0.0   9.17
72 2017-03-14    23    32    36   5.1  1.94   3.9  24.61
73 2017-03-15    22    25    28   0.0  0.00   3.9  21.25
74 2017-03-16    25    30    40   0.0  0.00   3.9  17.22
75 2017-03-17    30    36    45   0.0  0.00   3.1  13.20
76 2017-03-18    28    36    40   0.0  0.07   2.0  10.96
77 2017-03-19    35    40    48   0.0  0.00   1.2  14.54
78 2017-03-20    35    43    55   0.0  0.00   0.0  12.53
79 2017-03-21    42    49    57   0.0  0.00   0.0   9.17
80 2017-03-22    24    42    50   0.0  0.00   0.0  23.49
81 2017-03-23    23    31    44   0.0  0.00   0.0  11.63
82 2017-03-24    32    40    49   0.0  0.00   0.0  13.87
83 2017-03-25    42    51    62   0.0  0.01   0.0   8.72
84 2017-03-26    39    42    43   0.0  0.14   0.0  12.08
85 2017-03-27    40    45    58   0.0  0.19   0.0   6.04
86 2017-03-28    42    47    49   0.0  0.93   0.0   8.28
87 2017-03-29    42    49    61   0.0  0.00   0.0  16.33
88 2017-03-30    37    43    50   0.0  0.01   0.0   9.62
89 2017-03-31    39    41    42   0.0  2.07   0.0  16.11

In [21]:
weather_ = pd.concat([march_weather, jul_weather, oct_weather, dec_weather])

In [30]:
weather_.reset_index(inplace=True, drop=True)

In [31]:
merged = ride.sort_values(by=['month', 'day']).reset_index(drop=True).merge(weather_, left_index=True, right_index=True)

In [32]:
merged.head(10)

,day,month,weekday,year,isWeekend,isHoliday,customer,subscriber,index,DATE,TMIN,TAVG,TMAX,SNOW,PRCP,SNWD,AWND
0,1,3,2,2017,False,False,1027,39374,59,2017-03-01,48,51,61,0.0,0.01,0.0,11.63
1,2,3,3,2017,False,False,1006,34511,60,2017-03-02,37,52,62,0.0,0.00,0.0,25.50
2,3,3,4,2017,False,False,867,30060,61,2017-03-03,25,37,42,0.0,0.00,0.0,18.34
3,4,3,5,2017,True,False,549,14949,62,2017-03-04,18,27,34,0.0,0.00,0.0,20.80
4,5,3,6,2017,True,False,684,15076,63,2017-03-05,16,24,38,0.0,0.00,0.0,13.65
5,6,3,0,2017,False,False,912,31432,64,2017-03-06,22,32,42,0.0,0.00,0.0,8.05
6,7,3,1,2017,False,False,460,29114,65,2017-03-07,42,44,50,0.0,0.11,0.0,10.51
7,8,3,2,2017,False,False,1764,41408,66,2017-03-08,46,52,61,0.0,0.05,0.0,16.55
8,9,3,3,2017,False,False,1907,42959,67,2017-03-09,46,55,64,0.0,0.00,0.0,19.46
9,10,3,4,2017,False,False,222,18129,68,2017-03-10,24,42,49,2.4,0.26,0.0,17.45

In [33]:
merged.drop(['DATE', 'index'], axis=1, inplace=True)

In [34]:
merged.to_csv("data/ride_weather.csv", index=False)